### ISSUE TITLE
Downloaded and could not compile

### ISSUE THREAD

**Issue by gchudublin** [mathpaquette/IB.CSharpApiClient#5]
IB,CSharpAPI, IB.CSharpAPIClient source code? I installed from the NuGet package, not sure if I can get the source code.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'IB.CSharpApiClient.Extensions.EventExtensions.RaiseEvent<T>(System.EventHandler<T>, object, T)' and 'IB.CSharpApiClient.Extensions.EventExtensions.RaiseEvent<T>(System.EventHandler<T>, object, T)'	IB.CSharpApiClient	E:\code\amthpaquette\IB.CSharpApiClient-master\src\IB.CSharpApiClient\ApiEventDispatcher.cs	97	Active

**Comment by mathpaquette** [comment]
fixed on master
